### PR TITLE
convert test command to node script

### PR DESCRIPTION
**Pull request by ajrothwell**
I was unable to run the test command on windows because it uses bash syntax.  This pr converts that command to a node script that runs on all platforms.

### CODE REVIEW

**Comment by timwis** [comment]
Wow, cool! Code changes look good to me. If you can verify that this doesn't break existing functionality (it's currently running on a Linux box in aws) then I'd say you're good to merge!

On a separate note, Google chrome released a tool called puppeteer that is even easier to use than Casper. May be worth looking to that for the next version of this project, if there's still utility for it. And the graphcool team wrote a wrapper around it to run it as a lambda function, which is pretty cool (https://github.com/graphcool/chromeless)

**Comment by ajrothwell** [comment]
@timwis Sounds good. This is only changing the `test` command, and my guess is the Linux machine is using `server`, so we should be good.

This accidentally tried to deploy from the PR branch and failed -- we got an error that `deploy.sh exited wth a status of 1`. So the same thing will probably happen when we merge. Any ideas how Travis used to do that?

**Comment by ajrothwell** [comment]
Actually we figured it out -- we were looking at the wrong `deploy.sh`. Looks like it should work when we merge.

**Comment by rmx90210** [comment]
@timwis Puppeteer looks nice! I was actually meaning to ask if you'd consider a new branch of `interaction-testers` that swaps out Casper for one of the newer libraries. I've been looking into using Nightwatch for some of our other projects. Apparently there's a SaaS version in the works, which would be ideal, but still no word on it: https://nightcloud.io/

**Pull request merged**
